services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: carsale_elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: "false"
  mongodb:
    image: mongo:latest
    container_name: carsale_mongodb
    environment:
      - MONGO_INITDB_DATABASE=mongodb://localhost:27017
    ports:
     - 27017:27017